### PR TITLE
Add support for V4 data

### PR DESCRIPTION
**Pull request by CBroz1**
Work in progress. Still investigating how to best load V4 CSVs as annotations. 

In this PR, I propose ...
- Adopting `black` formatting, as is present in other CatalystNeuro works
- Additional device attributes that V4 stores as session metadata
- Adapt existing functions into a `MiniscopeLoader` class
- Adjust the usage instructions in the readme to reflect updates.

### CODE REVIEW

**Comment by bendichter** [comment]
@CBroz1 thanks for applying Black. I think that's a great idea, but would you mind separating the black from the other changes? It's difficult to review PRs when nearly every line is changed.

**Comment by CodyCBakerPhD** [comment]
> @CBroz1 thanks for applying Black. I think that's a great idea, but would you mind separating the black from the other changes? It's difficult to review PRs when nearly every line is changed.

I'll go ahead and set it up on a separate PR and enable the bot

**Comment by CBroz1** [comment]
Thanks @CodyCBakerPhD ! 

My black config may differ from your team's settings. If you include a `pyproject.toml`, I'll adopt those settings here

**Comment by bendichter** [comment]
thanks, guys

**Comment by CodyCBakerPhD** [comment]
Ahh, good ol' pre-commit conflicts

@CBroz1 If you re-run black locally instead of trying to resolve the conflicts, it *might* fix it automagically? 🤞

**Comment by CBroz1** [comment]
Thanks, @CodyCBakerPhD - I was able to fetch upstream and run pre-commit with the new config. I see your `toml` excludes the `docs` directory. Should I revert my blackified changes to scripts in this directory? e.g., `docs/source/conf.py`

I'm in the middle of another project now, but I can get in touch when I'm ready to bump this work to the top of my list. I don't yet have a plan for handling data like `headOrientation.csv` within my `MiniscopeLoader` class. This quaternion data may be present in V4 (but not v3) data.

**Comment by CodyCBakerPhD** [comment]
> Should I revert my blackified changes to scripts in this directory?

I'd say yes, sorry for the inconvenience there 😕


> I'm in the middle of another project now

No rush - for reviewing this we might want to eventually schedule a meeting and you can take me/us over it

I'd also greatly appreciate if there are any example files that could be shared publicly so we can setup proper tests+CI for this kind of thing

**Comment by CBroz1** [comment]
Closing as I won't be able to allocate time to this in the foreseeable future. Happy to share information about my progress if someone would like to take over from here.

**Pull request closed without merging**
